workflows:
  ios-workflow:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    working_directory: scs_go_flutter
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          flutter pub get
      - name: Create iOS platform
        script: |
          flutter create --platforms=ios .
      - name: Build iOS (no codesign)
        script: |
          flutter build ios --release --no-codesign
      - name: Package IPA
        script: |
          cd build/ios/iphoneos
          mkdir -p Payload
          mv Runner.app Payload/
          zip -r SCS-GO.ipa Payload
    artifacts:
      - build/ios/iphoneos/SCS-GO.ipa
      - build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - maitamit062005@gmail.com
