workflows:
  ios-workflow:
    name: iOS Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: |
          cd scs_go_flutter
          flutter packages pub get
      - name: Build iOS (no codesign)
        script: |
          cd scs_go_flutter
          flutter build ios --release --no-codesign
      - name: Package IPA
        script: |
          cd scs_go_flutter/build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r SCS-GO.ipa Payload
    artifacts:
      - scs_go_flutter/build/ios/iphoneos/SCS-GO.ipa
      - scs_go_flutter/build/ios/iphoneos/*.app
    publishing:
      email:
        recipients:
          - maitamit062005@gmail.com
